# Generated by Django 6.1 on 2026-09-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('print_type', models.CharField(max_length=100)),
                ('paper_size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('color_mode', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('print_status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
